### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by focuspadding** [suyuan32/goctls#92]
```
root/test# goctls rpc protoc ./rpc/article.proto --style=go_zero --go_out=./rpc/types --go-grpc_out=./rpc/types --zrpc_out=./rpc --style=go-zero -m

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xee0f08]

goroutine 1 [running]:
github.com/suyuan32/goctls/rpc/generator/proto.genProtoString({{0x0, 0x0}, {0xc00041542d, 0xb}, {0x0}, {0xc000382d1c, 0x2}, {0x0, 0x0}, {0x0, ...}, ...})
        /root/go/1.22.2/pkg/mod/github.com/suyuan32/goctls@v1.6.33/rpc/generator/proto/merge.go:150 +0x148
github.com/suyuan32/goctls/rpc/generator/proto.MergeProto(0xc00029f968)
        /root/go/1.22.2/pkg/mod/github.com/suyuan32/goctls@v1.6.33/rpc/generator/proto/merge.go:64 +0x445
github.com/suyuan32/goctls/rpc/generator.(*Generator).Generate(0xc000514980, 0xc00035e1a0)
        /root/go/1.22.2/pkg/mod/github.com/suyuan32/goctls@v1.6.33/rpc/generator/gen.go:89 +0x1a6
github.com/suyuan32/goctls/rpc/cli.ZRPC(0xc000001208?, {0xc00051bc70, 0x1, 0x7?})
        /root/go/1.22.2/pkg/mod/github.com/suyuan32/goctls@v1.6.33/rpc/cli/zrpc.go:109 +0x528
```

**Comment by suyuan32** [comment]
use `make gen-rpc`
